apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: documentation-example
  annotations:
    url: https://github.com/pmaganaOpenp/backstage-app/blob/main/components/chargebacks/README.md
spec:
  type: documentation
  lifecycle: experimental
  owner: openpay-chargebacks-team
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: dashboard-reloadCaches
  title: reloadCaches API
  description: Actualiza la configuración de tarjetas de cargo
spec:
  type: openapi
  lifecycle: production
  owner: openpay-chargebacks-team
  system: openpay-manager
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: updateCardChargeConfigurations API
      license:
        name: Apache 2.0
    servers:
      - url: http://openpay.mx/net/v1
    paths:
      /dashboard:
        put:
          summary: Reload Caches
    '200':
     description: a transantion to be returned
     content:
     application/json:
      schema:
        $ref: '#/reloadCaches/reloadCaches/{merchantId}'
