apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: openpay-manager
  title: Openpay Manager
  description: Encargado de ejecutar jobs cada X tiempo, los jobs tienen distintos propósitos, pero principalmente son para llevar a cabo procesos de conciliación
spec:
  owner: openpay-arquitectura
  domain: openpay-arquetipo-jobs
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: db-openpay
  title: Openppay DB
  description: Base de datos Openpay
spec:
  type: database
  owner: openpay-arquitectura
  system: openpay-manager
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: daily-chargeback-notification-job
  title: Daily Chargeback Notification Job
  description: Encargado de ejecutar jobs cada X tiempo, los jobs tienen distintos propósitos, pero principalmente son para llevar a cabo procesos de conciliación
  links:
    - url: https://bitbucket.org/openpay-dev/openpay/src/develop/mx.openpay.manager/src/main/java/mx/openpay/manager/jobs/DailyChargebackNotificationJob.java
      title: Bitbucket Java DailyChargebackNotificationJob
    - url: https://github.com/pmaganaOpenp/backstage-app/blob/main/components/chargebacks/tbl-asociadas-chargeback.txt
      title: Tablas asociadas
  tags:
    - mex
    - col
    - role+manager
    - internet+no
spec:
  type: service
  lifecycle: production
  owner: openpay-chargebacks-team
  domain: openpay-arquetipo-jobs
  system: openpay-manager
  dependsOn:
    - resource:default/db-openpay
  subcomponentOf: comercio-dashboard
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: comercio-dashboard
  title: Pantalla Comercio Dashboard
  description: Acceder al Dashboard a la pestaña de Aministracion y posteriormente a la pestaña Monitoreo cambios y posteriormente a Comercio
  links:
    - url: https://bitbucket.org/openpay-dev/openpay/src/develop/mx.openpay.dashboard/src/main/webapp/WEB-INF/pages/monitoring/monitoring-merchant-list.jsp
      title: monitoring-merchant-list.jsp
spec:
  type: website
  lifecycle: production
  owner: openpay-chargebacks-team
  domain: openpay-arquetipo-jobs
  system: openpay-manager
  dependsOn:
    - resource:default/db-openpay
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: api-charges-redirect-notificacion
  title: Servicio api charges/redirect/notitfication
  description: /v1/charges/redirect/notification/{redirectType}/{merchantId}
  tags:
    - get
    - post
    - text+plain
spec:
  type: service
  lifecycle: production
  owner: openpay-chargebacks-team
  domain: openpay-arquetipo-jobs
  system: openpay-manager
  dependsOn:
    - resource:default/db-openpay
  subcomponentOf: daily-chargeback-notification-job
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: openarch-job-azor-commons
  title: libreria openarch-job-azor-commons
  description: Libreria mx.openpay.oa:openarch-job-azor-commons
  links:
    - url: https://bitbucket.org/openpay-dev/openarch-job-azor-archetype
      title: mx.openpay.oa:openarch-job-azor-commons
spec:
  type: library
  lifecycle: production
  owner: openpay-arquitectura
  domain: openpay-arquetipo-jobs
  system: openpay-manager
---