apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mail-client-java
  title: libreria mail-client-java
  description: Libreria mx.openpay.oa:omail-client-java
  links:
    - url: https://bitbucket.org/openpay-dev/mail-client-pom
      title: mx.openpay.oa:openarch-job-azor-commons
spec:
  type: library
  lifecycle: production
  owner: openpay-arquitectura
  domain: openpay-arquetipo-jobs
  system: openpay-manager
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: documentation-example
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/pmaganaOpenp/backstage-app/blob/main/components/chargebacks/README.md
spec:
  type: documentation
  lifecycle: experimental
  owner: openpay-chargebacks-team