apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: org-data
spec:
  type: url
  targets:
    - https://github.com/pmaganaOpenp/backstage-app/blob/main/components/grupos-dev.yaml
    - https://github.com/pmaganaOpenp/backstage-app/blob/main/components/users-dev.yaml