---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: BackstagePOC
spec:
  owner: arch
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Manager-Jobs
spec:
  type: service
  lifecycle: experimental
  owner: arch
  system: BackstagePOC
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: openpay-dev-db
  description: Database openpay
spec:
  type: database
  owner: arch
  system: Manager-Jobs
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: openpay-dev-s3
  description: AWS S3 openpay
spec:
  type: s3-bucket
  owner: arch
  system: Manager-Jobs